name: Deploy WebSocket to Docker Hub

on:
  push:
    branches: [ main ]
    paths:
      - 'todo-app/apps/ws/**'
      - 'todo-app/packages/db/**'
      - 'todo-app/docker/Dockerfile.ws'

jobs: 
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Build and push websocket service
        uses: docker/build-push-action@v5
        with:
          context: ./todo-app
          file: ./todo-app/docker/Dockerfile.ws
          push: true
          tags: |
            omjaiswal241/todo-app-ws:latest
            omjaiswal241/todo-app-ws:${{ github.sha }}
